[mypy]
python_version = 3.11
disable_error_code = import-untyped

[mypy-transformers]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-datasets]
ignore_missing_imports = True

[mypy-datasets.*]
ignore_missing_imports = True

[mypy-auto_gptq]
ignore_missing_imports = True